name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
    - uses: actions/checkout@master
    - name: Install Conan
      run: pip install conan
    - name: Configure
      run: |
        cd ${{ github.workspace }}
        mkdir build
        cd build
        conan remote add -i 0 conancenter https://center.conan.io
        cmake --build .. --config Release --target CubeWorld_Editor
    - name: Build
      run: cd build && cmake --build .
